// constants/appointmentConstants.js

export const APPOINTMENT_CREATE_REQUEST = 'APPOINTMENT_CREATE_REQUEST';
export const APPOINTMENT_CREATE_SUCCESS = 'APPOINTMENT_CREATE_SUCCESS';
export const APPOINTMENT_CREATE_FAIL = 'APPOINTMENT_CREATE_FAIL';

export const APPOINTMENT_LIST_REQUEST = 'APPOINTMENT_LIST_REQUEST';
export const APPOINTMENT_LIST_SUCCESS = 'APPOINTMENT_LIST_SUCCESS';
export const APPOINTMENT_LIST_FAIL = 'APPOINTMENT_LIST_FAIL';

export const USER_APPOINTMENT_RESET = 'USER_APPOINTMENT_RESET';

export const APPOINTMENT_UPDATE_REQUEST = 'APPOINTMENT_UPDATE_REQUEST';
export const APPOINTMENT_UPDATE_SUCCESS = 'APPOINTMENT_UPDATE_SUCCESS';
export const APPOINTMENT_UPDATE_FAIL = 'APPOINTMENT_UPDATE_FAIL';

export const APPOINTMENT_DETAILS_REQUEST = 'APPOINTMENT_DETAILS_REQUEST';
export const APPOINTMENT_DETAILS_FAIL = 'APPPOINTMENT_DETAILS_FAIL';
export const APPOINTMENT_DETAILS_SUCCESS = 'APPOINTMENT_DETAILS_SUCCESS';

export const APPOINTMENT_PAY_REQUEST = 'APPOINTMENT_PAY_REQUEST';
export const APPOINTMENT_PAY_FAIL = 'APPPOINTMENT_PAY_FAIL';
export const APPOINTMENT_PAY_SUCCESS = 'APPOINTMENT_PAY_SUCCESS';
export const APPOINTMENT_PAY_RESET = 'APPOINTMENT_PAY_RESET';

export const APPOINTMENT_REVIEW_REQUEST = 'APPOINTMENT_REVIEW_REQUEST';
export const APPOINTMENT_REVIEW_FAIL = 'APPOINTMENT_REVIEW_FAIL';
export const APPOINTMENT_REVIEW_SUCCESS = 'APPOINTMENT_REVIEW_SUCCESS';

export const SAVE_ELAPSED_TIME = 'SAVE_ELAPSED_TIME';
