# Generated by Django 5.1 on 2024-10-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_doctorreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorreview',
            old_name='product',
            new_name='doctor',
        ),
    ]
