# Generated by Django 5.1 on 2024-10-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_appointment_paidat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
    ]
