# Generated by Django 5.1 on 2024-10-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreview',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='base.doctor'),
        ),
    ]
