# Generated by Django 5.1 on 2024-10-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_doctor_perhourrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='perhourRate',
            new_name='charge_rates',
        ),
    ]
