# Generated by Django 5.1 on 2024-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_perhourrate_doctor_charge_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='elapsed_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
