# Generated by Django 5.1 on 2024-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_appointment_elapsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chargeisPaid',
            field=models.BooleanField(default=False),
        ),
    ]
