# Generated by Django 5.1 on 2024-10-27 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_appointment_chargeispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreview',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
